"""
Django settings for InteractiveTranslation project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^@f24c3b-j&1z8l9^&8ut&bx7%2oz+hj%vt28g1k5dpre#t$5t'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
    

ALLOWED_HOSTS = ['*']


try:
    from .conf import *
except:
    DEBUG = True
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }
    SOCKETS = False
    PRODUCTION = False

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'mt',
    'mtsimple',
    'mtpara',
    # 'gpt',
]

if SOCKETS:
    INSTALLED_APPS.insert(0, 'channels')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'InteractiveTranslation.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'InteractiveTranslation.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
    

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

# STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

LOGIN_REDIRECT_URL = '/dashboard'
LOGOUT_REDIRECT_URL = '/accounts/login'

STATIC_LOCATION = "static"
MEDIA_LOCATION = "media"

if PRODUCTION:
    DEFAULT_FILE_STORAGE = 'InteractiveTranslation.custom_azure.AzureMediaStorage'
    STATICFILES_STORAGE = 'InteractiveTranslation.custom_azure.AzureStaticStorage'
    AZURE_ACCOUNT_NAME = "interactcentral"
    AZURE_CUSTOM_DOMAIN = f'{AZURE_ACCOUNT_NAME}.blob.core.windows.net'
    STATIC_URL = f'https://{AZURE_CUSTOM_DOMAIN}/{STATIC_LOCATION}/'
    MEDIA_URL = f'https://{AZURE_CUSTOM_DOMAIN}/{MEDIA_LOCATION}/'
else:
    STATIC_URL = '/static/'

# LOGGING = {
#  'version': 1,
#  'disable_existing_loggers': False,
#  'filters': {
#  'require_debug_false': {
#  '()': 'django.utils.log.RequireDebugFalse'
#  }
#  },
#  'handlers': {
#  'logfile': {
#  'class': 'logging.handlers.WatchedFileHandler',
#  'filename': 'D:\home\site\wwwroot\myapp.log'
#  }
#  },
#  'loggers': {
#  'django': {
#  'handlers': ['logfile'],
#  'level': 'ERROR',
#  'propagate': False,
#  }
#  }
#  }

if SOCKETS:
    ASGI_APPLICATION = 'InteractiveTranslation.routing.application'

DATA_UPLOAD_MAX_NUMBER_FIELDS = 5000

# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [("redis-server-name", 6379)],
#         },
#     },
# }