# Generated by Django 2.2 on 2019-04-22 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='corpusSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('corpus', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='translator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('gender', models.CharField(max_length=1)),
                ('dob', models.DateField()),
                ('updatedtime', models.DateTimeField(auto_now=True)),
                ('settime', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='translatedSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mt.corpusSet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'corpus')},
            },
        ),
        migrations.CreateModel(
            name='translatedSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=200)),
                ('tgt', models.CharField(max_length=200)),
                ('translatedSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mt.translatedSet')),
            ],
        ),
        migrations.CreateModel(
            name='time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thinktime', models.IntegerField()),
                ('writetime', models.IntegerField()),
                ('translatedSentence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mt.translatedSentence')),
            ],
        ),
        migrations.CreateModel(
            name='langtolang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srclang', to='mt.language')),
                ('tgt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tgtlang', to='mt.language')),
            ],
            options={
                'unique_together': {('src', 'tgt')},
            },
        ),
        migrations.CreateModel(
            name='keystrokes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.IntegerField()),
                ('enter', models.IntegerField()),
                ('up', models.IntegerField()),
                ('down', models.IntegerField()),
                ('space', models.IntegerField()),
                ('atoz', models.IntegerField()),
                ('pgdn', models.IntegerField()),
                ('pgup', models.IntegerField()),
                ('right', models.IntegerField()),
                ('left', models.IntegerField()),
                ('bkspc', models.IntegerField()),
                ('others', models.IntegerField()),
                ('translatedSentence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mt.translatedSentence')),
            ],
        ),
        migrations.CreateModel(
            name='translatorlangs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langtolang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mt.langtolang')),
                ('translator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mt.translator')),
            ],
            options={
                'unique_together': {('translator', 'langtolang')},
            },
        ),
    ]
