# Generated by Django 2.2 on 2019-04-22 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('corpus', models.TextField()),
                ('baselang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mt.language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='corpusLangReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mt.corpus')),
                ('langtolang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mt.langtolang')),
            ],
            options={
                'unique_together': {('corpus', 'langtolang')},
            },
        ),
        migrations.AlterField(
            model_name='translatedset',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mt.corpus'),
        ),
        migrations.DeleteModel(
            name='corpusSet',
        ),
    ]
