# Generated by Django 2.2 on 2019-04-22 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mt', '0002_auto_20190422_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatedset',
            name='langtolang',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mt.langtolang'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='translatedset',
            unique_together={('user', 'corpus', 'langtolang')},
        ),
    ]
