# Generated by Django 2.2 on 2019-04-23 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0003_auto_20190422_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpuslangreq',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corpuslangreqs', to='mt.corpus'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='translator', to=settings.AUTH_USER_MODEL),
        ),
    ]
