# Generated by Django 2.2 on 2019-04-24 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0004_auto_20190423_1902'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='translatedsentence',
            unique_together={('translatedSet', 'src')},
        ),
    ]
