# Generated by Django 2.2 on 2019-04-25 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0005_auto_20190424_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='corpusdivide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=200)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corpusdivide', to='mt.corpus')),
            ],
        ),
    ]
