# Generated by Django 2.2 on 2019-04-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0006_corpusdivide'),
    ]

    operations = [
        migrations.AddField(
            model_name='keystrokes',
            name='end',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
