# Generated by Django 2.2 on 2019-04-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0007_keystrokes_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keystrokes',
            name='atoz',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='keystrokes',
            name='bkspc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='keystrokes',
            name='down',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='keystrokes',
            name='end',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='keystrokes',
            name='enter',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='keystrokes',
            name='left',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='keystrokes',
            name='others',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='keystrokes',
            name='pgdn',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='keystrokes',
            name='pgup',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='keystrokes',
            name='right',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='keystrokes',
            name='space',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='keystrokes',
            name='tab',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='keystrokes',
            name='up',
            field=models.IntegerField(null=True),
        ),
    ]
