# Generated by Django 2.2 on 2019-06-05 07:31

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0009_auto_20190603_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corpus',
            options={'verbose_name': 'Corpus Identity', 'verbose_name_plural': '5. Corpus Identities'},
        ),
        migrations.AlterModelOptions(
            name='corpuslangreq',
            options={'verbose_name': 'Corpus Language Required', 'verbose_name_plural': '6. Corpus Languages Required'},
        ),
        migrations.AlterModelOptions(
            name='langtolang',
            options={'verbose_name': 'Language to Language Link', 'verbose_name_plural': '2. Language to Language Links'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Language', 'verbose_name_plural': '1. Languages'},
        ),
        migrations.AlterModelOptions(
            name='translator',
            options={'verbose_name': 'Translator Identity', 'verbose_name_plural': '3. Translator Identities'},
        ),
        migrations.AlterModelOptions(
            name='translatorlangs',
            options={'verbose_name': 'Translator Language Possible', 'verbose_name_plural': '4. Translator Languages Possible'},
        ),
        migrations.AlterField(
            model_name='translatorlangs',
            name='langtolang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translatorlangs', to='mt.langtolang'),
        ),
        migrations.AlterField(
            model_name='translatorlangs',
            name='translator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translatorlangs', to='mt.translator'),
        ),
        migrations.CreateModel(
            name='dockeystroke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keystrokeseries', jsonfield.fields.JSONField(default=dict)),
                ('trump', models.CharField(max_length=1)),
                ('translatedSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mt.translatedSet')),
            ],
            options={
                'verbose_name': 'Keystroke Time Series over the Document (Automatic)',
                'verbose_name_plural': 'Keystroke Time Series over the Document (Automatic)',
            },
        ),
    ]
