# Generated by Django 2.2 on 2019-06-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0010_auto_20190605_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='helpprovision',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
