# Generated by Django 2.2 on 2019-06-06 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0011_corpus_helpprovision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockeystroke',
            name='translatedSet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dockeystroke', to='mt.translatedSet'),
        ),
    ]
