# Generated by Django 2.2 on 2019-06-06 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0012_auto_20190606_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockeystroke',
            name='translatedSet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mt.translatedSet'),
        ),
    ]
