# Generated by Django 3.0.3 on 2020-05-19 16:12

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0014_auto_20190606_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='customKeyboardCommands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_entire_suggestion', models.IntegerField()),
                ('select_single_word_from_suggestion', models.IntegerField()),
                ('navigate_to_next_corpus_fragment', models.IntegerField()),
                ('navigate_to_previous_corpus_fragment', models.IntegerField()),
                ('submit_translation', models.IntegerField()),
                ('select_next_translation_suggestion', models.IntegerField()),
                ('select_previous_translation_suggestion', models.IntegerField()),
                ('custom_layout_name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Custom Keyboard Command Set',
                'verbose_name_plural': 'Custom Keyboard Command Sets',
            },
        ),
        migrations.AlterField(
            model_name='corpus',
            name='helpprovision',
            field=models.CharField(choices=[('IT', 'Interactive Translation'), ('PE', 'Post Editing'), ('BL', 'Baseline')], default='IT', max_length=2),
        ),
        migrations.AlterField(
            model_name='dockeystroke',
            name='keystrokeseries',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.CreateModel(
            name='translatorKeyboardLayouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customKeyboardCommands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translatorconfigs', to='mt.customKeyboardCommands')),
                ('translator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translatorconfigs', to='mt.translator')),
            ],
            options={
                'verbose_name': 'Translator Keyboard Layout Specified',
                'verbose_name_plural': 'Translator Keyboard Layout Specified',
                'unique_together': {('translator', 'customKeyboardCommands')},
            },
        ),
        migrations.CreateModel(
            name='translatorcorpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corpustranslators', to='mt.corpus')),
                ('translator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translatorcorpus', to='mt.translator')),
            ],
            options={
                'verbose_name': 'Translator Corpus Possible',
                'verbose_name_plural': '6. Translator Corpus Possible',
                'unique_together': {('translator', 'corpus')},
            },
        ),
    ]
